Premium template upgrades/fixes: Stripe + discount code closes#533
suredone/templates pull request #13
Opened 2021-08-16 12:32 UTC by velsvelmurugan

closes #https://github.com/suredone/automations/issues/533

Stripe upgrade and discount code html clean up.

2021-08-16 12:37 UTC, velsvelmurugan commented
@jasonspalace 

As per https://github.com/suredone/automations/issues/533 issue's reference:

- Added stripe by taking default-2019 as reference 
- Changed HTML content for discount view.

2021-08-16 13:23 UTC, jasonspalace requested changes
@velsvelmurugan was this tested? please see notes.

2021-08-16 13:23 UTC, jasonspalace commented on carpartstemplate/form-cardcheckout.htm
> +{% if not stripe %}
@velsvelmurugan where is `stripe` set?

2021-08-16 13:23 UTC, jasonspalace commented on innoinco/form-cardcheckout.htm
> +{% if not stripe %}
@velsvelmurugan where is `stripe` set?

2021-08-16 13:23 UTC, jasonspalace commented on shoestemplate/form-cardcheckout.htm
> +{% if not stripe %}
@velsvelmurugan where is `stripe` set?

2021-08-16 13:28 UTC, velsvelmurugan commented
@jasonspalace 
RE1:
No, it's not tested. I requested a review so I can test once you are ok with the changes.
RE2:
I just changed code in reference to https://github.com/suredone/templates/blob/master/default-2019/form-cardcheckout.htm#L103-L189 
Do I need to do like we did for other templates eg: https://github.com/suredone/automations/pull/391#issuecomment-769808022
?

2021-08-16 15:58 UTC, jasonspalace commented
@velsvelmurugan ok looks like it needs more work:

- the reference to `stripe` is being passed in from [`form-checkoutsteps.htm`](https://github.com/suredone/suredone/blob/master/flavors/default-2019/form-checkoutsteps.htm#L153) 
- also ensure you set the variable in this file
- must be applied to all carpartstemplate, innoinco, shoestemplate

2021-08-16 16:53 UTC, jasonspalace commented
@velsvelmurugan here is some reference to make it easier..

<img width="1215" alt="Screen Shot 2021-08-16 at 12 52 19 PM" src="https://user-images.githubusercontent.com/197291/129600304-effa974c-6fad-4a16-8381-72d8f46800af.png">
<img width="1215" alt="Screen Shot 2021-08-16 at 12 52 54 PM" src="https://user-images.githubusercontent.com/197291/129600380-68531b43-bf80-4f06-a4bb-159141bf6471.png">


Internal reference https://github.com/suredone/suredone/pull/2489

2021-08-17 13:21 UTC, jasonspalace approved these changes

2021-08-18 09:50 UTC, velsvelmurugan commented
@jasonspalace 

- Uploaded template files and assets of carpartstemplate, shoestemplate, innoinco in our ror test account.
- Tested Stripe Action

### Attachments:

### carpartstemplate:

![orderplaced](https://user-images.githubusercontent.com/50322284/129876927-8d9f2a18-d4ff-4eb0-bee6-f4752a341dda.png)
![stripecarparts](https://user-images.githubusercontent.com/50322284/129876938-699ff825-892e-4836-9994-17b25468cfc8.png)
![addressfillcarparts](https://user-images.githubusercontent.com/50322284/129876943-8ae227e2-19ce-41f9-89f2-1482d560a184.png)
![cartforcarparts](https://user-images.githubusercontent.com/50322284/129876950-eb662de2-5bbf-4c25-94f2-217a7fb31123.png)


-----


### shoestemplate
![stripeforshoestemplate](https://user-images.githubusercontent.com/50322284/129877167-4742d2a6-3207-45c1-b3b9-ce0a68ab7999.png)
![shoestemplateaddrform](https://user-images.githubusercontent.com/50322284/129877172-3851df21-0f6f-4e69-b002-3b295925c440.png)
![showtemplcarts](https://user-images.githubusercontent.com/50322284/129877177-29b47573-8d14-4919-8be3-67411ee74f8b.png)

![orderplacedshoestemplate](https://user-images.githubusercontent.com/50322284/129877155-1d53e370-7365-4387-be1b-ab5ba76371a9.png)


-----

### innoinco

![incoorderplaced](https://user-images.githubusercontent.com/50322284/129877511-3cabbb06-2689-4e00-8371-a57721f32779.png)
![incoaddressform](https://user-images.githubusercontent.com/50322284/129877523-2cafe1ea-e2ce-4f8e-820a-7bdc54b19b5a.png)
![incocart](https://user-images.githubusercontent.com/50322284/129877533-c49e4fc1-394e-446a-b55d-eab8d4301cb0.png)
![incostripe](https://user-images.githubusercontent.com/50322284/129877541-0f45a27e-3979-4f82-bceb-9536ac79bf50.png)

2021-08-18 12:51 UTC, merged